### ISSUE TITLE
✨ Design the XML Layout for Login/Signup Pages! 🖥️

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#3]
Your task is to design the XML layout for the Login and Signup screens of the app. The pages should be user-friendly, visually appealing, and responsive.

Requirements:
-->Login Page:
      Fields for Email/Username and Password.
      A Login button.
      A Forgot Password link.
      An option to Switch to Signup page (like a "Don't have an account? Signup here" text).

-->Signup Page:
      Fields for Name, Email, and Password.
      A Signup button.
      An option to Switch to Login page (like a "Already have an account? Login here" text).

For reference, please check the app's Figma design [Readme.md](https://github.com/opencodeiiita/Huddle/blob/main/Readme.md) or attached image.

![image](https://github.com/user-attachments/assets/1d696696-6f36-4525-896e-586b718132bc)

Note:-This issue is first-come, first-served 🏃‍♂️, so be sure to claim it before starting.
Deadline: 2 days from claim date ⏰

**Comment by MonuGit9** [comment]
Claim

**Comment by Aryan9059** [comment]
Claim.

**Comment by official-ashutosh** [comment]
claim
