### ISSUE TITLE
🔑 Design the XML for Forgot Password Page! ✨

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#4]
Your task is to create the XML layout for the Forgot Password screen , OTP verification Screen and Password Updation Screen. The all 3 pages should be responsive 📱. 
For reference, please check the app's Figma design [Readme.md](https://github.com/opencodeiiita/Huddle/blob/main/Readme.md) or attached image.
![image](https://github.com/user-attachments/assets/bccafcbe-795a-4b6a-8db2-a0fa04d4e632)

-->Note :- This issue is first-come, first-served 🏃‍♂️, so be sure to claim it before starting.
Deadline: 3 days from claim date ⏰

**Comment by MonuGit9** [comment]
Claim

**Comment by Aryan9059** [comment]
Claim.

**Comment by deadmoont** [comment]
@MonuGit9  has already assigned with 2 task currently and one open for all ....so this task will be assigned to @Aryan9059

**Comment by sahilgupta2006** [comment]
claim

**Comment by Aryan9059** [comment]
Created Pull Request
