### ISSUE TITLE
📱 Simplify Navigation, Amplify Engagement! 🔥

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#41]
Hey Contributors😊,

-->Implement a Bottom Navigation Bar
        Add sections for Home 🏠, Project 📁, Community 💬, and Profile 👤.
        Include a central "Plus" button ➕ with a distinct design (e.g., floating or highlighted).

-->Icon Placement and Styling
        Ensure icons are visually balanced and spaced appropriately.
        Use responsive design to fit different screen sizes.

-->Functionality
      Add click events to navigate to corresponding pages/screens.
      Implement active state (highlight the current active section).

-->Design Consistency 🎨
    Match the navigation bar with the app's existing theme.
    Ensure colors, fonts, and styles align with the app's UI/UX.
    
You can follow the attached design to implement the following things 
![image](https://github.com/user-attachments/assets/37f0f495-97e6-4b6f-9e29-cb6f76dc9c35)
![image](https://github.com/user-attachments/assets/0f302c45-63e9-4620-9ac5-2dc0b4010fd5)

⏰Deadline
     2 days from claim date

**Comment by PriyamJChakrabarty** [comment]
claim
