### ISSUE TITLE
✨ Let’s supercharge task management! ✨

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#45]
Hey Contributors! 😊

This screen is designed to organize tasks in style. Your mission, should you choose to accept it:

1️⃣ 👥 Add Team Members: Make it visual and engaging!
2️⃣ 📅 Set Dates: Simplify planning with precise date pickers.
3️⃣ ⏰ Manage Time: Implement intuitive start and end time inputs.
4️⃣ 📂 Categorize Tasks: Create dynamic boards (Urgent, Running, Ongoing).

🎯 What to do?

🔧 Create a UI for this Screen
➕ Add a Fragment:
        ->  Make a new fragment for task creation.
        ->  Connect it to the Crete Task option present in plus icon in the bottom sheet layout.
🎨 Follow the sleek and modern design below!
💻 Let’s make task management as seamless as possible! 🚀
![image](https://github.com/user-attachments/assets/3f431c9f-db38-4ac5-8287-d624ce3c663e)

⏰Deadline
     2 days from claim date

**Comment by Aryan9059** [comment]
Claim

**Comment by Aryan9059** [comment]
Sir how can I link the fragment to the bottom nav, it is not in the code.

**Comment by deadmoont** [comment]
see the showBottomsheet function in the BaseHomeActivity . there has been implemented the part of close button .....there you have to write the code of set on click listener for the create task ...whose id you can see from the bottom_sheet_layout.xml

**Comment by Aryan9059** [comment]
Sorry I didn't sync my fork earlier. I'm almost don't but I'm not able to change app:strokeColor attribute of the Board chips whenever they are checked and unchecked.
