### ISSUE TITLE
✨ Unlock Your Identity ✨

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#46]
Hey Contributors! 😊,
This screen is your go-to hub for managing tasks and projects efficiently. Here’s what you can do:

👤 View Profile Details:

Your name and email displayed prominently for easy recognition.
📊 Track Progress:

Ongoing Tasks: Stay on top of your active projects.
Completed Tasks: Celebrate your achievements with a tally of completed tasks.
📁 Explore Options:

   1️⃣  My Projects: View and manage all your projects.
   2️⃣ Join a Team: Collaborate and grow with your team.
   3️⃣ Settings: Customize your experience.
   4️⃣ My Task: Dive into the specifics of your task list.
🎯 Edit Made Easy:
Easily update your profile details with the Edit button for a seamless user experience.

Stay organized and in control, all from one place! 🚀

![image](https://github.com/user-attachments/assets/2ac370c5-86f2-47f5-9734-b64c465bb424)
⏰Deadline
     2 days from claim date

**Comment by PriyamJChakrabarty** [comment]
claim
