### ISSUE TITLE
🚀 Build Your Dream Team Interface

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#50]
Introducing a sleek and intuitive interface to form your team! 🌟

🎨 Custom Branding: Upload your team logo to make it stand out.
       -->User should be able to upload image from gallery .
🖋️ Personalized Team Name: Give your team an identity with a unique name.
👥 Add Members with Ease: Quickly add team members and visualize them with profile avatars.
🔒 Control Visibility: Set your team’s privacy with options like Private, Public, or Secret.
✅ One-Click Team Creation: Complete setup with a single tap on the “Create Team” button.

This feature enhances collaboration and branding, making it perfect for any team-building scenario!

You have to make the XML for the following feature . For reference you can follow the attached image .

![image](https://github.com/user-attachments/assets/e374f959-f4c9-4cf1-bd73-1ee1b1da222c)

⏰Deadline
2 days from claim date

**Comment by Aryan9059** [comment]
Claim
