### ISSUE TITLE
🛠️ Create Project Form UI Enhancement 🚀

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#55]
This page allows users to create a new project effortlessly by providing essential project details in an intuitive and visually appealing form. Here's a breakdown of the key features:

1️⃣ Project Name: Add a meaningful title for the project.
2️⃣ Add Members: Select team members with a seamless user interface.
3️⃣ Date and Time: Set project start and end dates using the calendar picker.
4️⃣ Labels: Categorize your project with custom tags for better organization.
5️⃣ Description: Add a brief description of the project's purpose and scope.
6️⃣ Create Button: A call-to-action to finalize and save the project details.

🎯 Objective
Enhance the functionality and aesthetics of the "Create Project" form, ensuring an exceptional user experience and ease of use.
       🖌️ Tasks
            1️⃣ Improve interactivity of date, member, and label pickers.
            2️⃣ Ensure proper validation and error handling for all fields.
            3️⃣ Make the "Create" button visually engaging and responsive.
            
You can follow the attached design but make sure the background is dark not white.

![image](https://github.com/user-attachments/assets/6828e163-cfe6-4fbc-a03c-4b58ed428da6)

⏰Deadline
    2 days from claim date

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by Aryan9059** [comment]
Claim

**Comment by deadmoont** [comment]
@Aryan9059 you can claim the backend task
