### ISSUE TITLE
🔐 Feature Request: Implement Firebase Login & Signup Functionality

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#56]
We need to add a secure and user-friendly Login & Signup feature to our app using Firebase Authentication. This feature will allow users to:

🔑 Sign up with their email and password.
🔄 Log in using their existing credentials.
🚪 Log out securely when they are done.

🎯 Expected Behavior
1️⃣ Users should be able to create an account using Firebase Authentication.
2️⃣ Users can log in using their registered email and password.
3️⃣ Proper error handling (e.g., invalid email, weak password, user not found).
4️⃣ UI feedback for ongoing operations (e.g., loading spinners).

🛠 Technical Details
1️⃣ Use Firebase Authentication SDK for integration.
2️⃣ Ensure compatibility with existing project libraries and architecture.
3️⃣ Follow best practices for authentication and security.

Let’s empower users to securely access their accounts! 🚀

⏰Deadline
    2 days from claim date

**Comment by Aryan9059** [comment]
Claim

**Comment by Aryan9059** [comment]
aryansrivastava9059@gmail.com

**Comment by deadmoont** [comment]
You would have got the mail regarding this
