### ISSUE TITLE
🚀 Project Dashboard: Track & Achieve📂

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#61]
🔷 1. Task Collection Setup
📋 Collection Name: Project

    Fields:
    📝 projectName – The name of the project.
    🖊️ projectDesc – A brief description of the project.
    📈 projectProgress – Progress percentage of the task.
    🧮 totalTask – Total number of tasks in the project.
         MembersList-the members details

🔧 Steps to Implement:
    1️⃣ Create a collection in Firestore named Project.
    2️⃣ Populate it with dummy data simulating ongoing projects (e.g., web design, app development).
    3️⃣ Fetch and display these tasks dynamically on the home page under the "Ongoing Projects" section.

🔷 2. My Task Collection Setup
📋 Collection Name: myTask

    Fields:
        📝 name – Personalized task name.
        🖊️ desc – Detailed task description.
        📅 taskDate – Scheduled date for the task.
        📈 taskProgress – Task completion progress.

🔧 Steps to Implement:
      1️⃣ Create a Firestore collection named myTask.
      2️⃣ Add dummy personalized tasks to represent individual projects.
      3️⃣ Display these tasks dynamically on the home page .
            
Note:  Ensure that the design is visually appealing and that the integration with Firestore is seamless. Dummy data should be representative of real-world scenarios to showcase the functionality effectively.

You can follow the below design to display the data of "my task" and "Task".
![image](https://github.com/user-attachments/assets/308326d4-5080-4e5f-9507-85003b72e0ab)

**Comment by Aryan9059** [comment]
Claim
