### ISSUE TITLE
 🕒 Beat the Clock: Sleek Settings

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#63]
Create the XML layout for the Settings Page based on the provided design. The page includes:

  🔒 Toggle switches for Permissions, Push Notifications, and Dark Mode.
  📂 Navigation options for Security, Help, and About Application.
  🎨 A dark theme layout with modern aesthetics.

💡 Note: Focus solely on creating the XML structure. Implementation and functionality of components will be handled later.
You can follow the below design .
![image](https://github.com/user-attachments/assets/fb1a997b-a1ab-4f20-be0b-6958997634eb)
🕒 Deadline: 
     2 Days from assign date.

**Comment by PriyamJChakrabarty** [comment]
claim

**Comment by deadmoont** [comment]
@PriyamJChakrabarty what is the status of work

**Comment by PriyamJChakrabarty** [comment]
@deadmoont going good...will create a pr soon
