### ISSUE TITLE
✨ Effortless Creation of New Additions 🚧

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#69]
👋 Hey Contributors!

🌟 After completing the Home Page functionality, let's move on to implementing the Add Project backend!

📋 Here's the plan:

🖼️ The XML for the form is all set and ready to go!
🖱️ On Submit, a brand-new project should be added seamlessly.
👥 Make sure we can also add members while creating the project.
🚀 Let's bring this feature to life—happy coding! 💻✨

**Comment by Aryan9059** [comment]
Claim

**Comment by official-ashutosh** [comment]
Claim
