### ISSUE TITLE
🚀 Enhancing Project and Task Tracking Features

### ISSUE THREAD

**Issue by ParadoxNJ005** [opencodeiiita/Huddle#72]
👋 Hey Contributors!

🌟 Let’s supercharge our app with the Search Feature, All Tab, and Task Status Page functionality!

📋 Here's the plan:

🔍 1️⃣ Search Feature:
      🎯 Add a search bar to filter projects by name or tags.
      ⏱️ Use debounce for smooth and responsive typing.
      ⚡ Show a loader while searching and display "No results found" if no matches.

  📂 2️⃣ All Tab:
        📋 Add an "All" tab to showcase a full list of projects.
        🌐 Fetch all projects via API and manage large lists with pagination.

🛠️ 3️⃣ Task Status Page:
        📌 Open this page when clicking on any project.
        📊 Display task statuses in categories like "To Do," "In Progress," and "Completed."
        ✨ Use a clean and user-friendly UI design inspired by the provided reference.

📌 Design References:
    🖼️ Here's the project page design you can use for the layout:

![image](https://github.com/user-attachments/assets/7d7494dc-5378-425f-9dec-b3b8a22d3a53)
    
    🖼️ Here's the task status page design to follow:

![image](https://github.com/user-attachments/assets/779507bb-f67a-44b3-9959-1a36ae98bc92)

🚀 Let’s make this happen—happy coding, team! 💻✨

**Comment by Aryan9059** [comment]
claim
