### ISSUE TITLE
Brighten Your App Experience! 🌟

### ISSUE THREAD

**Issue by deadmoont** [opencodeiiita/Huddle#75]
Implement a feature to allow users to toggle between dark mode 🌑 and light mode ☀️. This toggle is located on the Settings page, which is accessible through the Profile page 👤. Ensure the following:

🌟 UI Update:
      🔄 Add an intuitive 🌑☀️ switch on the Settings page (via Profile 👤).
      🎨 Ensure the mode change reflects instantly across all screens of the app.

📅 Deadline: 2 days ⏳

**Comment by official-ashutosh** [comment]
Claim

**Comment by deadmoont** [comment]
@official-ashutosh u already have 3 task so i cant assign you with this task!!

**Comment by official-ashutosh** [comment]
Actually I have completed codebuddy issue....

**Comment by Aryan9059** [comment]
claim

**Comment by deadmoont** [comment]
@official-ashutosh according to rules i cant assign you the task
